### ISSUE TITLE
Can I change the filed message to log?

### ISSUE THREAD

**Issue by lizhongit** [fluent/fluent-plugin-parser-cri#9]
I already have a EFK for running on, and all of the logs will into a JSON struct with a log field, in my case, I have a k8s that is running on Containerd, so use fluent-plugin-parser-cri working around, but How can I change the filed 'message' to 'log', it real import for me.

**Comment by Ga13Ou** [comment]
@lizhongit 
Found a solution to do that natively or you just used a record_transformer filter?
